Repository olmangjolmang/omjm-server, pull requests merged in 2024-07, with the labels that each got.

#9 로그인 및 회원가입
  build.gradle
  src/main/java/com/ticle/server/global/config/SecurityConfig.java
  src/main/java/com/ticle/server/user/controller/EmailController.java
  src/main/java/com/ticle/server/user/controller/UserController.java
  src/main/java/com/ticle/server/user/domain/User.java
  src/main/java/com/ticle/server/user/dto/EmailDto.java
  src/main/java/com/ticle/server/user/dto/JoinRequest.java
  src/main/java/com/ticle/server/user/dto/JwtToken.java
  src/main/java/com/ticle/server/user/dto/LoginRequest.java
  src/main/java/com/ticle/server/user/dto/UserDto.java
  src/main/java/com/ticle/server/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ticle/server/user/jwt/JwtTokenProvider.java
  src/main/java/com/ticle/server/user/jwt/SecurityUtil.java
  src/main/java/com/ticle/server/user/repository/UserRepository.java
  src/main/java/com/ticle/server/user/service/CustomUserDetailsService.java
  src/main/java/com/ticle/server/user/service/EmailService.java
  src/main/java/com/ticle/server/user/service/EmailServiceImpl.java
  src/main/java/com/ticle/server/user/service/UserService.java
Labels: ✨ Feature, 📬 API

#11 카테고리별 아티클 정보 가져오기
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/domain/Post.java
  src/main/java/com/ticle/server/post/dto/PostResponse.java
  src/main/java/com/ticle/server/post/repository/PostRepository.java
  src/main/java/com/ticle/server/post/service/PostService.java
  src/main/resources/data.sql
  src/test/java/com/ticle/server/ServerApplicationTests.java
Labels: ✨ Feature, 📬 API

#13 마이페이지-저장한 아티클
  src/main/java/com/ticle/server/mypage/controller/MyQuestionController.java
  src/main/java/com/ticle/server/mypage/dto/MyQuestionDto.java
  src/main/java/com/ticle/server/mypage/dto/SavedTicleDto.java
  src/main/java/com/ticle/server/mypage/service/MyPageService.java
  src/main/java/com/ticle/server/post/domain/Post.java
  src/main/java/com/ticle/server/post/repository/PostRepository.java
  src/main/java/com/ticle/server/scrapped/domain/Scrapped.java
  src/main/java/com/ticle/server/talk/domain/Talk.java
  src/main/java/com/ticle/server/user/domain/User.java
  src/main/resources/data.sql
Labels: ✨ Feature, 📬 API

#16 게시글 스크랩/스크랩 취소 기능 구현
  src/main/java/com/ticle/server/global/config/SecurityConfig.java
  src/main/java/com/ticle/server/memo/domain/Memo.java
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/domain/Post.java
  src/main/java/com/ticle/server/post/repository/PostRepository.java
  src/main/java/com/ticle/server/post/service/PostService.java
  src/main/java/com/ticle/server/scrapped/controller/ScrappedApiController.java
  src/main/java/com/ticle/server/scrapped/domain/Scrapped.java
  src/main/java/com/ticle/server/scrapped/dto/ScrappedDto.java
  src/main/java/com/ticle/server/scrapped/repository/ScrappedRepository.java
  src/main/java/com/ticle/server/scrapped/service/ScrappedService.java
  src/main/java/com/ticle/server/user/controller/UserController.java
  src/main/java/com/ticle/server/user/domain/User.java
  src/main/resources/data.sql
Labels: ✨ Feature, 📬 API

#18 메모 기능 구현
  src/main/java/com/ticle/server/memo/controller/MemoApiController.java
  src/main/java/com/ticle/server/memo/domain/Memo.java
  src/main/java/com/ticle/server/memo/dto/MemoDto.java
  src/main/java/com/ticle/server/memo/dto/MemoRequest.java
  src/main/java/com/ticle/server/memo/repository/MemoRepository.java
  src/main/java/com/ticle/server/memo/service/MemoService.java
  src/main/java/com/ticle/server/mypage/repository/MemoRepository.java
  src/main/java/com/ticle/server/mypage/service/MyPageService.java
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: ✨ Feature, 📬 API, 🌱 enhance

#19 아티클 페이징 처리
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/repository/PostRepository.java
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: ✨ Feature, 🌱 enhance

#20 아티클 가져오는 controller 경량화
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: 🔨 Refactor, 🌱 enhance

#22 생성형 AI Gemini 도입, 함께 읽으면 좋은 아티클 기능 구현
  src/main/java/com/ticle/server/ServerApplication.java
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/domain/Post.java
  src/main/java/com/ticle/server/post/dto/GeminiRequest.java
  src/main/java/com/ticle/server/post/dto/GeminiResponse.java
  src/main/java/com/ticle/server/post/dto/GeminiRestTemplateConfig.java
  src/main/java/com/ticle/server/post/dto/PostIdTitleDto.java
  src/main/java/com/ticle/server/post/dto/PostResponse.java
  src/main/java/com/ticle/server/post/repository/PostRepository.java
  src/main/java/com/ticle/server/post/service/PostService.java
  src/main/resources/data.sql
Labels: ✨ Feature, 📬 API, 🌱 enhance

#25 티클창고- userId 수정
  src/main/java/com/ticle/server/mypage/controller/MyQuestionController.java
  src/main/java/com/ticle/server/mypage/controller/SavedTicleController.java
  src/main/java/com/ticle/server/mypage/dto/MyNoteDto.java
  src/main/java/com/ticle/server/mypage/dto/UpdateCommentDto.java
  src/main/java/com/ticle/server/mypage/repository/NoteRepository.java
  src/main/java/com/ticle/server/mypage/repository/ScrapRepository.java
  src/main/java/com/ticle/server/mypage/service/MyPageService.java
  src/main/java/com/ticle/server/opinion/repository/CommentRepository.java
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: 🔨 Refactor, 🌱 enhance

#26 티클문답 - 마이페이지에서 수정/삭제
  src/main/java/com/ticle/server/global/config/SecurityConfig.java
  src/main/java/com/ticle/server/mypage/controller/MyQuestionController.java
  src/main/java/com/ticle/server/mypage/controller/SavedTicleController.java
  src/main/java/com/ticle/server/user/controller/EmailController.java
  src/main/java/com/ticle/server/user/jwt/JwtTokenProvider.java
  src/main/java/com/ticle/server/user/service/UserService.java
Labels: ✨ Feature

#24 아티클 내용 기반 퀴즈 생성
  .gitignore
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/domain/Post.java
  src/main/java/com/ticle/server/post/domain/Quiz.java
  src/main/java/com/ticle/server/post/dto/GeminiResponse.java
  src/main/java/com/ticle/server/post/dto/QuizResponse.java
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: ✨ Feature, 📬 API

#27 CI/CD 에러 수정
  src/main/java/com/ticle/server/memo/domain/Memo.java
  src/main/java/com/ticle/server/post/domain/Post.java
Labels: 🐞 BugFix

#28 버그 수정
  src/main/java/com/ticle/server/mypage/controller/NoteController.java
  src/main/java/com/ticle/server/mypage/controller/QuestionController.java
  src/main/java/com/ticle/server/mypage/repository/QuestionRepository.java
  src/main/java/com/ticle/server/mypage/repository/ScrapRepository.java
  src/main/java/com/ticle/server/mypage/service/MyPageService.java
  src/main/java/com/ticle/server/opinion/repository/CommentRepository.java
  src/main/java/com/ticle/server/opinion/repository/OpinionRepository.java
  src/main/java/com/ticle/server/scrapped/repository/ScrappedRepository.java
  src/main/java/com/ticle/server/user/repository/UserRepository.java
Labels: 🐞 BugFix

#23 SUBSCRIPTION 기능 구현
  src/main/java/com/ticle/server/global/config/SchedulerConfig.java
  src/main/java/com/ticle/server/home/controller/HomeController.java
  src/main/java/com/ticle/server/home/domain/Subscription.java
  src/main/java/com/ticle/server/home/dto/request/SubscriptionRequest.java
  src/main/java/com/ticle/server/home/dto/request/ValidEmailRequest.java
  src/main/java/com/ticle/server/home/dto/request/ValidateNickNameRequest.java
  src/main/java/com/ticle/server/home/repository/SubscriptionRepository.java
  src/main/java/com/ticle/server/home/service/HomeService.java
  src/main/java/com/ticle/server/home/service/SchedulingService.java
  src/main/java/com/ticle/server/opinion/controller/OpinionController.java
  src/main/java/com/ticle/server/opinion/service/OpinionService.java
  src/main/java/com/ticle/server/post/domain/Post.java
  src/main/java/com/ticle/server/post/exception/PostNotFoundException.java
  src/main/java/com/ticle/server/post/exception/errorcode/PostErrorCode.java
  src/main/java/com/ticle/server/post/repository/PostRepository.java
  src/main/java/com/ticle/server/user/exception/UserNotFoundException.java
  src/main/java/com/ticle/server/user/exception/errorcode/UserErrorCode.java
  src/main/java/com/ticle/server/user/repository/UserRepository.java
  src/main/java/com/ticle/server/user/service/EmailService.java
Labels: ✨ Feature, 📬 API, 🌱 enhance

#31 Gemini 빈 리스트 리턴 예외 처리
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: 🐞 BugFix, 🌱 enhance

#29 post 최신순으로 정렬 & post 스크랩 수 추가
  src/main/java/com/ticle/server/memo/domain/Memo.java
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/domain/Post.java
  src/main/java/com/ticle/server/post/service/PostService.java
  src/main/java/com/ticle/server/scrapped/domain/Scrapped.java
  src/main/java/com/ticle/server/user/service/UserService.java
Labels: ✨ Feature, 🌱 enhance

#32 마이페이지-티클노트 수정 삭제 기능 추가
  src/main/java/com/ticle/server/ServerApplication.java
  src/main/java/com/ticle/server/memo/domain/Memo.java
  src/main/java/com/ticle/server/mypage/controller/NoteController.java
  src/main/java/com/ticle/server/mypage/controller/QuestionController.java
  src/main/java/com/ticle/server/mypage/controller/SavedTicleController.java
  src/main/java/com/ticle/server/mypage/dto/request/CommentUpdateRequest.java
  src/main/java/com/ticle/server/mypage/dto/request/NoteUpdateRequest.java
  src/main/java/com/ticle/server/mypage/dto/response/NoteResponse.java
  src/main/java/com/ticle/server/mypage/dto/response/QuestionResponse.java
  src/main/java/com/ticle/server/mypage/dto/response/SavedTicleResponse.java
  src/main/java/com/ticle/server/mypage/service/MyPageService.java
  src/main/java/com/ticle/server/post/service/PostService.java
  src/main/java/com/ticle/server/user/domain/User.java
Labels: ✨ Feature, 📬 API

#38 구독하기 이메일과 닉네임 삭제
  src/main/java/com/ticle/server/home/controller/HomeController.java
  src/main/java/com/ticle/server/home/domain/Subscription.java
  src/main/java/com/ticle/server/home/dto/request/SubscriptionRequest.java
  src/main/java/com/ticle/server/home/dto/request/ValidEmailRequest.java
  src/main/java/com/ticle/server/home/dto/request/ValidateNickNameRequest.java
  src/main/java/com/ticle/server/home/service/HomeService.java
  src/main/java/com/ticle/server/home/service/SchedulingService.java
Labels: 🔨 Refactor

#42 ✨ Feat: 아티클 검색 기능 구현
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/repository/PostRepository.java
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: ✨ Feature, 🌱 enhance

#43 홈화면과 티클문답 오류 수정
  src/main/java/com/ticle/server/global/config/SecurityConfig.java
  src/main/java/com/ticle/server/global/dto/PageInfo.java
  src/main/java/com/ticle/server/opinion/dto/response/OpinionResponseList.java
  src/main/java/com/ticle/server/opinion/service/OpinionService.java
  src/main/java/com/ticle/server/user/exception/errorcode/UserErrorCode.java
Labels: 🐞 BugFix, 🌱 enhance

#44 유저 - 비밀번호 일치 여부, 프로필 수정 기능 | CORS config 추가
  src/main/java/com/ticle/server/global/config/CorsConfig.java
  src/main/java/com/ticle/server/user/controller/UserController.java
  src/main/java/com/ticle/server/user/domain/User.java
  src/main/java/com/ticle/server/user/dto/request/ProfileUpdateRequest.java
  src/main/java/com/ticle/server/user/exception/InvalidPasswordException.java
  src/main/java/com/ticle/server/user/service/CustomUserDetailsService.java
  src/main/java/com/ticle/server/user/service/UserService.java
Labels: ✨ Feature, 📃 Docs

#39 홈 화면 정보 제공
  src/main/java/com/ticle/server/global/config/GeminiRestTemplateConfig.java
  src/main/java/com/ticle/server/home/controller/HomeController.java
  src/main/java/com/ticle/server/home/dto/response/HomeResonse.java
  src/main/java/com/ticle/server/home/dto/response/HomeResponse.java
  src/main/java/com/ticle/server/home/dto/response/PostSetsResponse.java
  src/main/java/com/ticle/server/home/service/HomeService.java
  src/main/java/com/ticle/server/home/service/PostTopicCache.java
  src/main/java/com/ticle/server/home/service/SchedulingService.java
  src/main/java/com/ticle/server/post/dto/GeminiResponse.java
  src/main/java/com/ticle/server/post/repository/PostRepository.java
Labels: ✨ Feature, 📬 API

#46 유저 -프로필 및 관심 카테고리 수정
  src/main/java/com/ticle/server/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ticle/server/user/controller/UserController.java
  src/main/java/com/ticle/server/user/dto/request/CategoryUpdateRequest.java
  src/main/java/com/ticle/server/user/dto/request/JoinRequest.java
  src/main/java/com/ticle/server/user/dto/request/ProfileUpdateRequest.java
  src/main/java/com/ticle/server/user/exception/InvalidPasswordException.java
  src/main/java/com/ticle/server/user/service/UserService.java
Labels: ✨ Feature, 🌱 enhance

#47 티클문답 관련 수정사항
  src/main/java/com/ticle/server/opinion/controller/OpinionController.java
  src/main/java/com/ticle/server/opinion/dto/response/CommentResponseList.java
  src/main/java/com/ticle/server/opinion/service/OpinionService.java
Labels: 🌱 enhance

#48 유저 - 프로필 수정 및 Category 리스트로 수정
  src/main/java/com/ticle/server/post/repository/PostRepository.java
  src/main/java/com/ticle/server/user/domain/User.java
  src/main/java/com/ticle/server/user/dto/request/CategoryUpdateRequest.java
  src/main/java/com/ticle/server/user/dto/request/JoinRequest.java
  src/main/java/com/ticle/server/user/dto/response/UserResponse.java
  src/main/java/com/ticle/server/user/repository/init/UserInitializer.java
Labels: 🐞 BugFix

#49 :bug: Fix: 유저 아이디 제대로 안나오는 오류 수정
  src/main/java/com/ticle/server/opinion/service/OpinionService.java
Labels: 🐞 BugFix

#56 #51 change post recommend process
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/domain/Post.java
  src/main/java/com/ticle/server/post/dto/GeminiResponse.java
  src/main/java/com/ticle/server/post/dto/ReadRecommendPost.java
  src/main/java/com/ticle/server/post/repository/PostRepository.java
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: 📬 API, 🌱 enhance

#58 ✨ Feat: 특정 아티클에 대한 저장 유무
  src/main/java/com/ticle/server/post/controller/PostApiController.java
  src/main/java/com/ticle/server/post/dto/PostIsSavedResponse.java
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: ✨ Feature, 📬 API

#60 ✅ Test: 하드 데이터 삭제 후 크롤링 데이터로 quiz 생성 테스트
  src/main/java/com/ticle/server/post/service/PostService.java
Labels: 🔨 Refactor, ✅ Test
